//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.APP_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLevelRevokeHistory
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string VIPMemberID { get; set; }
        public Nullable<System.DateTime> PromotedDate { get; set; }
        public string Note { get; set; }
        public System.DateTime ActionOn { get; set; }
        public int ActionBy { get; set; }
        public bool Active { get; set; }
    }
}
